### ISSUE TITLE
NOT'ing 8-bit expressions results in wider values

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#212]
For instance, once would expect `db ~$40` to work as `db $bf`, but it is an error instead.

**Comment by AntonioND** [comment]
This one is tricky. You can't know if the value is supposed to be 8 bit wide, 16 or 32. Even if it is obvious because of the context (the result is passed to `DB`, for example), the result of the NOT may be used in a temporary value that is shifted right, and that results in a valid value. I imagine that "-"  (change sign) has a similar problem. And there is only one function to do this, `rpn_UNNOT()`.

I was thinking about having a new variable like `expr->isReloc` or `expr->isPCRel` with the original size of the constant and, when trying to do the final assignment, check if the original size was the same one as the destination one, and don't complain in that case. The problem is that there may be any number of operations in between, and any of them could increase the size to 16 or 32 bits. In that case, it would make sense to error.

The only thing we can do is to turn that error into a warning...

**Comment by aaaaaa123456789** [comment]
Another possibility is to conceal the warning only if the discarded bits are all set (as well as all clear, as it is the case currently) — that is, if the value is greater than or equal to `$ffffff00` for 8-bit expressions and `$ffff0000` for 16-bit ones.

Note that I said `$ffffff00`, not `$ffffff80`; this is because expressions like `~$80` (with an apparent value of `$ffffff7f`) should be legitimate 8-bit expressions.

(As for the unary minus, I've been told that it only barfs for values in the upper half of the valid range: `-$7f` works as intended, but `-$80` breaks. I haven't been able to verify this, but the approach mentioned above would solve this issue as well.)

**Comment by AntonioND** [comment]
The problem is that the code uses the stupid `SLONG`, `SSHORT`, etc, types. When this program was developed `long` was probably 32-bit wide, so everything worked (`NOT` is calculated as `x ^ 0xFFFFFFFF`). Now it is 64-bit wide, and some things break.

I'm going to change the operator to `~` as it should have been from the start, and change the types. I'm pretty sure that this will fix everything without having to resort to what you say. After all, it's working with negative values because the negative value isn't calculated by hand...

I'll have to change a lot of `printf` too, let's see how painful this change turns out to be...

**Comment by AntonioND** [comment]
Should be fixed in #213. If it isn't, reopen this issue.

**Comment by Rangi42** [comment]
This is still an issue. As of 0.3.7 the following cases work as expected:

```
SLP EQU %111
	ld b, ~SLP
```

```
	db ~(1 << 3)
```

```
x = 3
	db ~(1 << x)
```

There `~(X)` is equivalent to `$ff ^ (X)`.

But the following cases fail to compile, saying "Expression must be 8-bit":

```
	and ~(1 << 7)
```

```
x = 0
rept 8
	db ~(1 << x)
x = x + 1
endr
```
